[package]
name = "simple-http-server"
version = "0.1.0"
authors = ["stevesternberg"]
edition = "2021"

[dependencies]
http = "1.0.0"
bytes = "1.0.1"
lazy_static = "1.4.0"
chrono = "0.4.19"

[dependencies.uuid]
version = "1.6.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
